### PR TITLE
Feature/enriched logger

### PR DESCRIPTION
**Pull request by MatteoGioioso**
I have added more context to Sentry.

#### New Tags
- Function name
- Log stream name

#### Context
- Function name
- Log group name
- Full link to the Cloudwatch logs in production

### Result
You can see how the new error will be displayed in the UI

image

### CODE REVIEW

**Comment by superical** [comment]
Cool addition to the logger!👏  Sounds like it could help with referencing errors. For the log stream, I'm just afraid whether it would end up creating too many tags for each one of them, would it? If we could have the name of the log stream printed out in the Sentry alert details instead of creating a tag for each one of them, it might be better.

**Comment by superical** [comment]
Ahh... Okay, I just read the code. You had the tag as StreamName. I read from the description and was thinking differently just now. haha... I think this could work then!

**Comment by MatteoGioioso** [comment]
@superical Oh yes, actually I did not think about that, then I guess we should just keep the function name in the tags and that's it.
Anyway the other values are in the context which will not be indexed

**Comment by MatteoGioioso** [comment]
@superical actually you were right because the `StreamName` as tag will be indexed, and I think we don't needed it

**Comment by superical** [comment]
@MatteoGioioso Okay, I just did a quick check on the tags with the test alerts you have triggered. It seems like we will have too many of them even when we grouped them under the StreamName tag. Yea, we can probably keep the function name but not the stream name.

**Comment by MatteoGioioso** [comment]
@superical ok I have fixed it

**Review by superical — APPROVED** [review]
Looks good!👍

**Pull request merged**
